# Generated by Django 3.2.21 on 2024-07-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240715_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Posts',
        ),
    ]
